---
- hosts: all
  become: yes
  tasks:
   - name: i want to install server on ubuntu
     apt:
         name: apache2
         state: present 
   - name:
     service:
         name: apache2
         state: started 