---
- hosts: mywebserver
  become: yes
  tasks:
   - name: i want to install server on ubuntu
     apt:
         name: "{{mywebpackonubuntu}}"
         state: present
     when: ansible_os_family== "Debian"
   - name:
     service:
         name: "{{mywebpackonubuntu}}"
         state: started 
     when: ansible_os_family== "Debian" 
   - name: i want to install webserver on redhat
     dnf:
          name: "{{mywebpackonredhat}}"
          state: present
     when: ansible_os_family== "RedHat" 
   - name: i want to start webserver on redhat
     service:
          name: "{{mywebpackonredhat}}"
          state: started
     when: ansible_os_family== "RedHat"      
